### ISSUE TITLE
PC版在遇到“下一页”按钮时会跳转但跳转后不会继续自动下滑

### ISSUE THREAD

**Issue by LonginusL33T** [DoooReyn/WxRead-PC-AutoReader#3]
win10 21H2 64位  

如题，如果是遇到“下一章”按钮，会自动跳转且继续自动下滑。但遇到同一章却分页的情况下无法自动继续。必须要手动按两下F10才能开启自动下滑。

**Comment by LonginusL33T** [comment]
最近发现, "下一页"的按钮并不是每本书都有。比如 阿西莫夫的银河帝国只有“下一章”，所以自动阅读可以持续到最后。但是 白鹿原  每一章里还分页。遇到“下一页”时自动阅读会停止。

**Comment by DoooReyn** [comment]
> 最近发现, "下一页"的按钮并不是每本书都有。比如 阿西莫夫的银河帝国只有“下一章”，所以自动阅读可以持续到最后。但是 白鹿原 每一章里还分页。遇到“下一页”时自动阅读会停止。

开发时只看到下一章，没想到还有下一页。

下个版本计划修复此问题。

**Comment by LonginusL33T** [comment]
感谢

**Comment by DoooReyn** [comment]
新版本已修复，可以关注一下。

LonginusL33T ***@***.***> 于2022年9月29日周四 09:30写道：

**Comment by LonginusL33T** [comment]
舒服了，正在体验，谢谢大佬
